// Code generated by Kitex v0.16.1. DO NOT EDIT.

package groupservice

import (
	kitexgroupservie "aim/kitex_gen/kitexgroupservie"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetGroupInfo(ctx context.Context, req *kitexgroupservie.GetGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupInfoResp, err error)
	ChangeGroupInfo(ctx context.Context, req *kitexgroupservie.ChangeGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservie.ChangeGroupInfoResp, err error)
	SearchGroup(ctx context.Context, req *kitexgroupservie.SearchGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.SearchGroupResp, err error)
	CreateGroup(ctx context.Context, req *kitexgroupservie.CreateGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.CreateGroupResp, err error)
	DeleteGroup(ctx context.Context, req *kitexgroupservie.DeleteGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.DeleteGroupResp, err error)
	LeaveGroup(ctx context.Context, req *kitexgroupservie.LeaveGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.LeaveGroupResp, err error)
	SetGroupApply(ctx context.Context, req *kitexgroupservie.SetGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetGroupApplyResp, err error)
	GetGroupApplyList(ctx context.Context, req *kitexgroupservie.GetGroupApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupApplyListResp, err error)
	GetLastVisitTime(ctx context.Context, req *kitexgroupservie.GetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetLastVisitTimeResp, err error)
	AgreeGroupApply(ctx context.Context, req *kitexgroupservie.AgreeGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.AgreeGroupApplyResp, err error)
	TransformGroupOwner(ctx context.Context, req *kitexgroupservie.TransformGroupOwnerReq, callOptions ...callopt.Option) (r *kitexgroupservie.TransformGroupOwnerResp, err error)
	KickOutGroup(ctx context.Context, req *kitexgroupservie.KickOutGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.KickOutGroupResp, err error)
	SetManager(ctx context.Context, req *kitexgroupservie.SetManagerReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetManagerResp, err error)
	RevokeManager(ctx context.Context, req *kitexgroupservie.RevokeManagerReq, callOptions ...callopt.Option) (r *kitexgroupservie.RevokeManagerResp, err error)
	GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.GetGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupInfoWithUserResp, err error)
	UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.UpdateGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservie.UpdateGroupInfoWithUserResp, err error)
	CreatSession(ctx context.Context, req *kitexgroupservie.CreatSessionReq, callOptions ...callopt.Option) (r *kitexgroupservie.CreatSessionResp, err error)
	DeleteSession(ctx context.Context, req *kitexgroupservie.DeleteSessionReq, callOptions ...callopt.Option) (r *kitexgroupservie.DeleteSessionResp, err error)
	GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservie.GetFriendLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetFriendLastVisitTimeResp, err error)
	ApplyForFriend(ctx context.Context, req *kitexgroupservie.ApplyForFriendReq, callOptions ...callopt.Option) (r *kitexgroupservie.ApplyForFriendResp, err error)
	GetFriendApplyList(ctx context.Context, req *kitexgroupservie.GetFriendApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetFriendApplyListResp, err error)
	RefuseFriendApply(ctx context.Context, req *kitexgroupservie.RefuseFriendApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.RefuseFriendApplyResp, err error)
	GetGroupAndSessionID(ctx context.Context, req *kitexgroupservie.GetGroupAndSessionIDReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupAndSessionIDResp, err error)
	SetMute(ctx context.Context, req *kitexgroupservie.SetMuteReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetMuteResp, err error)
	ReleaseMute(ctx context.Context, req *kitexgroupservie.ReleaseMuteReq, callOptions ...callopt.Option) (r *kitexgroupservie.ReleaseMuteResp, err error)
	GetMuteStatus(ctx context.Context, req *kitexgroupservie.GetMuteStatusReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetMuteStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kGroupServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGroupServiceClient struct {
	*kClient
}

func (p *kGroupServiceClient) GetGroupInfo(ctx context.Context, req *kitexgroupservie.GetGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupInfo(ctx, req)
}

func (p *kGroupServiceClient) ChangeGroupInfo(ctx context.Context, req *kitexgroupservie.ChangeGroupInfoReq, callOptions ...callopt.Option) (r *kitexgroupservie.ChangeGroupInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeGroupInfo(ctx, req)
}

func (p *kGroupServiceClient) SearchGroup(ctx context.Context, req *kitexgroupservie.SearchGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.SearchGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchGroup(ctx, req)
}

func (p *kGroupServiceClient) CreateGroup(ctx context.Context, req *kitexgroupservie.CreateGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.CreateGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateGroup(ctx, req)
}

func (p *kGroupServiceClient) DeleteGroup(ctx context.Context, req *kitexgroupservie.DeleteGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.DeleteGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteGroup(ctx, req)
}

func (p *kGroupServiceClient) LeaveGroup(ctx context.Context, req *kitexgroupservie.LeaveGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.LeaveGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LeaveGroup(ctx, req)
}

func (p *kGroupServiceClient) SetGroupApply(ctx context.Context, req *kitexgroupservie.SetGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetGroupApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetGroupApply(ctx, req)
}

func (p *kGroupServiceClient) GetGroupApplyList(ctx context.Context, req *kitexgroupservie.GetGroupApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupApplyListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupApplyList(ctx, req)
}

func (p *kGroupServiceClient) GetLastVisitTime(ctx context.Context, req *kitexgroupservie.GetLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetLastVisitTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastVisitTime(ctx, req)
}

func (p *kGroupServiceClient) AgreeGroupApply(ctx context.Context, req *kitexgroupservie.AgreeGroupApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.AgreeGroupApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AgreeGroupApply(ctx, req)
}

func (p *kGroupServiceClient) TransformGroupOwner(ctx context.Context, req *kitexgroupservie.TransformGroupOwnerReq, callOptions ...callopt.Option) (r *kitexgroupservie.TransformGroupOwnerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TransformGroupOwner(ctx, req)
}

func (p *kGroupServiceClient) KickOutGroup(ctx context.Context, req *kitexgroupservie.KickOutGroupReq, callOptions ...callopt.Option) (r *kitexgroupservie.KickOutGroupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.KickOutGroup(ctx, req)
}

func (p *kGroupServiceClient) SetManager(ctx context.Context, req *kitexgroupservie.SetManagerReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetManagerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetManager(ctx, req)
}

func (p *kGroupServiceClient) RevokeManager(ctx context.Context, req *kitexgroupservie.RevokeManagerReq, callOptions ...callopt.Option) (r *kitexgroupservie.RevokeManagerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeManager(ctx, req)
}

func (p *kGroupServiceClient) GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.GetGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupInfoWithUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupInfoWithUser(ctx, req)
}

func (p *kGroupServiceClient) UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.UpdateGroupInfoWithUserReq, callOptions ...callopt.Option) (r *kitexgroupservie.UpdateGroupInfoWithUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateGroupInfoWithUser(ctx, req)
}

func (p *kGroupServiceClient) CreatSession(ctx context.Context, req *kitexgroupservie.CreatSessionReq, callOptions ...callopt.Option) (r *kitexgroupservie.CreatSessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatSession(ctx, req)
}

func (p *kGroupServiceClient) DeleteSession(ctx context.Context, req *kitexgroupservie.DeleteSessionReq, callOptions ...callopt.Option) (r *kitexgroupservie.DeleteSessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteSession(ctx, req)
}

func (p *kGroupServiceClient) GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservie.GetFriendLastVisitTimeReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetFriendLastVisitTimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendLastVisitTime(ctx, req)
}

func (p *kGroupServiceClient) ApplyForFriend(ctx context.Context, req *kitexgroupservie.ApplyForFriendReq, callOptions ...callopt.Option) (r *kitexgroupservie.ApplyForFriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyForFriend(ctx, req)
}

func (p *kGroupServiceClient) GetFriendApplyList(ctx context.Context, req *kitexgroupservie.GetFriendApplyListReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetFriendApplyListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendApplyList(ctx, req)
}

func (p *kGroupServiceClient) RefuseFriendApply(ctx context.Context, req *kitexgroupservie.RefuseFriendApplyReq, callOptions ...callopt.Option) (r *kitexgroupservie.RefuseFriendApplyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefuseFriendApply(ctx, req)
}

func (p *kGroupServiceClient) GetGroupAndSessionID(ctx context.Context, req *kitexgroupservie.GetGroupAndSessionIDReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetGroupAndSessionIDResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetGroupAndSessionID(ctx, req)
}

func (p *kGroupServiceClient) SetMute(ctx context.Context, req *kitexgroupservie.SetMuteReq, callOptions ...callopt.Option) (r *kitexgroupservie.SetMuteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetMute(ctx, req)
}

func (p *kGroupServiceClient) ReleaseMute(ctx context.Context, req *kitexgroupservie.ReleaseMuteReq, callOptions ...callopt.Option) (r *kitexgroupservie.ReleaseMuteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseMute(ctx, req)
}

func (p *kGroupServiceClient) GetMuteStatus(ctx context.Context, req *kitexgroupservie.GetMuteStatusReq, callOptions ...callopt.Option) (r *kitexgroupservie.GetMuteStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMuteStatus(ctx, req)
}
