// Code generated by Kitex v0.16.1. DO NOT EDIT.

package groupservice

import (
	kitexgroupservie "aim/kitex_gen/kitexgroupservie"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetGroupInfo": kitex.NewMethodInfo(
		getGroupInfoHandler,
		newGroupServiceGetGroupInfoArgs,
		newGroupServiceGetGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeGroupInfo": kitex.NewMethodInfo(
		changeGroupInfoHandler,
		newGroupServiceChangeGroupInfoArgs,
		newGroupServiceChangeGroupInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchGroup": kitex.NewMethodInfo(
		searchGroupHandler,
		newGroupServiceSearchGroupArgs,
		newGroupServiceSearchGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateGroup": kitex.NewMethodInfo(
		createGroupHandler,
		newGroupServiceCreateGroupArgs,
		newGroupServiceCreateGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteGroup": kitex.NewMethodInfo(
		deleteGroupHandler,
		newGroupServiceDeleteGroupArgs,
		newGroupServiceDeleteGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LeaveGroup": kitex.NewMethodInfo(
		leaveGroupHandler,
		newGroupServiceLeaveGroupArgs,
		newGroupServiceLeaveGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetGroupApply": kitex.NewMethodInfo(
		setGroupApplyHandler,
		newGroupServiceSetGroupApplyArgs,
		newGroupServiceSetGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupApplyList": kitex.NewMethodInfo(
		getGroupApplyListHandler,
		newGroupServiceGetGroupApplyListArgs,
		newGroupServiceGetGroupApplyListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLastVisitTime": kitex.NewMethodInfo(
		getLastVisitTimeHandler,
		newGroupServiceGetLastVisitTimeArgs,
		newGroupServiceGetLastVisitTimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AgreeGroupApply": kitex.NewMethodInfo(
		agreeGroupApplyHandler,
		newGroupServiceAgreeGroupApplyArgs,
		newGroupServiceAgreeGroupApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TransformGroupOwner": kitex.NewMethodInfo(
		transformGroupOwnerHandler,
		newGroupServiceTransformGroupOwnerArgs,
		newGroupServiceTransformGroupOwnerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"KickOutGroup": kitex.NewMethodInfo(
		kickOutGroupHandler,
		newGroupServiceKickOutGroupArgs,
		newGroupServiceKickOutGroupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetManager": kitex.NewMethodInfo(
		setManagerHandler,
		newGroupServiceSetManagerArgs,
		newGroupServiceSetManagerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeManager": kitex.NewMethodInfo(
		revokeManagerHandler,
		newGroupServiceRevokeManagerArgs,
		newGroupServiceRevokeManagerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupInfoWithUser": kitex.NewMethodInfo(
		getGroupInfoWithUserHandler,
		newGroupServiceGetGroupInfoWithUserArgs,
		newGroupServiceGetGroupInfoWithUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateGroupInfoWithUser": kitex.NewMethodInfo(
		updateGroupInfoWithUserHandler,
		newGroupServiceUpdateGroupInfoWithUserArgs,
		newGroupServiceUpdateGroupInfoWithUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatSession": kitex.NewMethodInfo(
		creatSessionHandler,
		newGroupServiceCreatSessionArgs,
		newGroupServiceCreatSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteSession": kitex.NewMethodInfo(
		deleteSessionHandler,
		newGroupServiceDeleteSessionArgs,
		newGroupServiceDeleteSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendLastVisitTime": kitex.NewMethodInfo(
		getFriendLastVisitTimeHandler,
		newGroupServiceGetFriendLastVisitTimeArgs,
		newGroupServiceGetFriendLastVisitTimeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ApplyForFriend": kitex.NewMethodInfo(
		applyForFriendHandler,
		newGroupServiceApplyForFriendArgs,
		newGroupServiceApplyForFriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFriendApplyList": kitex.NewMethodInfo(
		getFriendApplyListHandler,
		newGroupServiceGetFriendApplyListArgs,
		newGroupServiceGetFriendApplyListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefuseFriendApply": kitex.NewMethodInfo(
		refuseFriendApplyHandler,
		newGroupServiceRefuseFriendApplyArgs,
		newGroupServiceRefuseFriendApplyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetGroupAndSessionID": kitex.NewMethodInfo(
		getGroupAndSessionIDHandler,
		newGroupServiceGetGroupAndSessionIDArgs,
		newGroupServiceGetGroupAndSessionIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetMute": kitex.NewMethodInfo(
		setMuteHandler,
		newGroupServiceSetMuteArgs,
		newGroupServiceSetMuteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReleaseMute": kitex.NewMethodInfo(
		releaseMuteHandler,
		newGroupServiceReleaseMuteArgs,
		newGroupServiceReleaseMuteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMuteStatus": kitex.NewMethodInfo(
		getMuteStatusHandler,
		newGroupServiceGetMuteStatusArgs,
		newGroupServiceGetMuteStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	groupServiceServiceInfo                = NewServiceInfo()
	groupServiceServiceInfoForClient       = NewServiceInfoForClient()
	groupServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return groupServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return groupServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "GroupService"
	handlerType := (*kitexgroupservie.GroupService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexgroupservie",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetGroupInfoArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetGroupInfoResult)
	success, err := handler.(kitexgroupservie.GroupService).GetGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupInfoArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupInfoArgs()
}

func newGroupServiceGetGroupInfoResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupInfoResult()
}

func changeGroupInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceChangeGroupInfoArgs)
	realResult := result.(*kitexgroupservie.GroupServiceChangeGroupInfoResult)
	success, err := handler.(kitexgroupservie.GroupService).ChangeGroupInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceChangeGroupInfoArgs() interface{} {
	return kitexgroupservie.NewGroupServiceChangeGroupInfoArgs()
}

func newGroupServiceChangeGroupInfoResult() interface{} {
	return kitexgroupservie.NewGroupServiceChangeGroupInfoResult()
}

func searchGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceSearchGroupArgs)
	realResult := result.(*kitexgroupservie.GroupServiceSearchGroupResult)
	success, err := handler.(kitexgroupservie.GroupService).SearchGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSearchGroupArgs() interface{} {
	return kitexgroupservie.NewGroupServiceSearchGroupArgs()
}

func newGroupServiceSearchGroupResult() interface{} {
	return kitexgroupservie.NewGroupServiceSearchGroupResult()
}

func createGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceCreateGroupArgs)
	realResult := result.(*kitexgroupservie.GroupServiceCreateGroupResult)
	success, err := handler.(kitexgroupservie.GroupService).CreateGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCreateGroupArgs() interface{} {
	return kitexgroupservie.NewGroupServiceCreateGroupArgs()
}

func newGroupServiceCreateGroupResult() interface{} {
	return kitexgroupservie.NewGroupServiceCreateGroupResult()
}

func deleteGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceDeleteGroupArgs)
	realResult := result.(*kitexgroupservie.GroupServiceDeleteGroupResult)
	success, err := handler.(kitexgroupservie.GroupService).DeleteGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceDeleteGroupArgs() interface{} {
	return kitexgroupservie.NewGroupServiceDeleteGroupArgs()
}

func newGroupServiceDeleteGroupResult() interface{} {
	return kitexgroupservie.NewGroupServiceDeleteGroupResult()
}

func leaveGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceLeaveGroupArgs)
	realResult := result.(*kitexgroupservie.GroupServiceLeaveGroupResult)
	success, err := handler.(kitexgroupservie.GroupService).LeaveGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceLeaveGroupArgs() interface{} {
	return kitexgroupservie.NewGroupServiceLeaveGroupArgs()
}

func newGroupServiceLeaveGroupResult() interface{} {
	return kitexgroupservie.NewGroupServiceLeaveGroupResult()
}

func setGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceSetGroupApplyArgs)
	realResult := result.(*kitexgroupservie.GroupServiceSetGroupApplyResult)
	success, err := handler.(kitexgroupservie.GroupService).SetGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSetGroupApplyArgs() interface{} {
	return kitexgroupservie.NewGroupServiceSetGroupApplyArgs()
}

func newGroupServiceSetGroupApplyResult() interface{} {
	return kitexgroupservie.NewGroupServiceSetGroupApplyResult()
}

func getGroupApplyListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetGroupApplyListArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetGroupApplyListResult)
	success, err := handler.(kitexgroupservie.GroupService).GetGroupApplyList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupApplyListArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupApplyListArgs()
}

func newGroupServiceGetGroupApplyListResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupApplyListResult()
}

func getLastVisitTimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetLastVisitTimeArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetLastVisitTimeResult)
	success, err := handler.(kitexgroupservie.GroupService).GetLastVisitTime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetLastVisitTimeArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetLastVisitTimeArgs()
}

func newGroupServiceGetLastVisitTimeResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetLastVisitTimeResult()
}

func agreeGroupApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceAgreeGroupApplyArgs)
	realResult := result.(*kitexgroupservie.GroupServiceAgreeGroupApplyResult)
	success, err := handler.(kitexgroupservie.GroupService).AgreeGroupApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceAgreeGroupApplyArgs() interface{} {
	return kitexgroupservie.NewGroupServiceAgreeGroupApplyArgs()
}

func newGroupServiceAgreeGroupApplyResult() interface{} {
	return kitexgroupservie.NewGroupServiceAgreeGroupApplyResult()
}

func transformGroupOwnerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceTransformGroupOwnerArgs)
	realResult := result.(*kitexgroupservie.GroupServiceTransformGroupOwnerResult)
	success, err := handler.(kitexgroupservie.GroupService).TransformGroupOwner(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceTransformGroupOwnerArgs() interface{} {
	return kitexgroupservie.NewGroupServiceTransformGroupOwnerArgs()
}

func newGroupServiceTransformGroupOwnerResult() interface{} {
	return kitexgroupservie.NewGroupServiceTransformGroupOwnerResult()
}

func kickOutGroupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceKickOutGroupArgs)
	realResult := result.(*kitexgroupservie.GroupServiceKickOutGroupResult)
	success, err := handler.(kitexgroupservie.GroupService).KickOutGroup(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceKickOutGroupArgs() interface{} {
	return kitexgroupservie.NewGroupServiceKickOutGroupArgs()
}

func newGroupServiceKickOutGroupResult() interface{} {
	return kitexgroupservie.NewGroupServiceKickOutGroupResult()
}

func setManagerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceSetManagerArgs)
	realResult := result.(*kitexgroupservie.GroupServiceSetManagerResult)
	success, err := handler.(kitexgroupservie.GroupService).SetManager(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSetManagerArgs() interface{} {
	return kitexgroupservie.NewGroupServiceSetManagerArgs()
}

func newGroupServiceSetManagerResult() interface{} {
	return kitexgroupservie.NewGroupServiceSetManagerResult()
}

func revokeManagerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceRevokeManagerArgs)
	realResult := result.(*kitexgroupservie.GroupServiceRevokeManagerResult)
	success, err := handler.(kitexgroupservie.GroupService).RevokeManager(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceRevokeManagerArgs() interface{} {
	return kitexgroupservie.NewGroupServiceRevokeManagerArgs()
}

func newGroupServiceRevokeManagerResult() interface{} {
	return kitexgroupservie.NewGroupServiceRevokeManagerResult()
}

func getGroupInfoWithUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetGroupInfoWithUserArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetGroupInfoWithUserResult)
	success, err := handler.(kitexgroupservie.GroupService).GetGroupInfoWithUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupInfoWithUserArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupInfoWithUserArgs()
}

func newGroupServiceGetGroupInfoWithUserResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupInfoWithUserResult()
}

func updateGroupInfoWithUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceUpdateGroupInfoWithUserArgs)
	realResult := result.(*kitexgroupservie.GroupServiceUpdateGroupInfoWithUserResult)
	success, err := handler.(kitexgroupservie.GroupService).UpdateGroupInfoWithUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceUpdateGroupInfoWithUserArgs() interface{} {
	return kitexgroupservie.NewGroupServiceUpdateGroupInfoWithUserArgs()
}

func newGroupServiceUpdateGroupInfoWithUserResult() interface{} {
	return kitexgroupservie.NewGroupServiceUpdateGroupInfoWithUserResult()
}

func creatSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceCreatSessionArgs)
	realResult := result.(*kitexgroupservie.GroupServiceCreatSessionResult)
	success, err := handler.(kitexgroupservie.GroupService).CreatSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceCreatSessionArgs() interface{} {
	return kitexgroupservie.NewGroupServiceCreatSessionArgs()
}

func newGroupServiceCreatSessionResult() interface{} {
	return kitexgroupservie.NewGroupServiceCreatSessionResult()
}

func deleteSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceDeleteSessionArgs)
	realResult := result.(*kitexgroupservie.GroupServiceDeleteSessionResult)
	success, err := handler.(kitexgroupservie.GroupService).DeleteSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceDeleteSessionArgs() interface{} {
	return kitexgroupservie.NewGroupServiceDeleteSessionArgs()
}

func newGroupServiceDeleteSessionResult() interface{} {
	return kitexgroupservie.NewGroupServiceDeleteSessionResult()
}

func getFriendLastVisitTimeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetFriendLastVisitTimeArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetFriendLastVisitTimeResult)
	success, err := handler.(kitexgroupservie.GroupService).GetFriendLastVisitTime(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetFriendLastVisitTimeArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetFriendLastVisitTimeArgs()
}

func newGroupServiceGetFriendLastVisitTimeResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetFriendLastVisitTimeResult()
}

func applyForFriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceApplyForFriendArgs)
	realResult := result.(*kitexgroupservie.GroupServiceApplyForFriendResult)
	success, err := handler.(kitexgroupservie.GroupService).ApplyForFriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceApplyForFriendArgs() interface{} {
	return kitexgroupservie.NewGroupServiceApplyForFriendArgs()
}

func newGroupServiceApplyForFriendResult() interface{} {
	return kitexgroupservie.NewGroupServiceApplyForFriendResult()
}

func getFriendApplyListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetFriendApplyListArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetFriendApplyListResult)
	success, err := handler.(kitexgroupservie.GroupService).GetFriendApplyList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetFriendApplyListArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetFriendApplyListArgs()
}

func newGroupServiceGetFriendApplyListResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetFriendApplyListResult()
}

func refuseFriendApplyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceRefuseFriendApplyArgs)
	realResult := result.(*kitexgroupservie.GroupServiceRefuseFriendApplyResult)
	success, err := handler.(kitexgroupservie.GroupService).RefuseFriendApply(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceRefuseFriendApplyArgs() interface{} {
	return kitexgroupservie.NewGroupServiceRefuseFriendApplyArgs()
}

func newGroupServiceRefuseFriendApplyResult() interface{} {
	return kitexgroupservie.NewGroupServiceRefuseFriendApplyResult()
}

func getGroupAndSessionIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetGroupAndSessionIDArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetGroupAndSessionIDResult)
	success, err := handler.(kitexgroupservie.GroupService).GetGroupAndSessionID(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetGroupAndSessionIDArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupAndSessionIDArgs()
}

func newGroupServiceGetGroupAndSessionIDResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetGroupAndSessionIDResult()
}

func setMuteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceSetMuteArgs)
	realResult := result.(*kitexgroupservie.GroupServiceSetMuteResult)
	success, err := handler.(kitexgroupservie.GroupService).SetMute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceSetMuteArgs() interface{} {
	return kitexgroupservie.NewGroupServiceSetMuteArgs()
}

func newGroupServiceSetMuteResult() interface{} {
	return kitexgroupservie.NewGroupServiceSetMuteResult()
}

func releaseMuteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceReleaseMuteArgs)
	realResult := result.(*kitexgroupservie.GroupServiceReleaseMuteResult)
	success, err := handler.(kitexgroupservie.GroupService).ReleaseMute(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceReleaseMuteArgs() interface{} {
	return kitexgroupservie.NewGroupServiceReleaseMuteArgs()
}

func newGroupServiceReleaseMuteResult() interface{} {
	return kitexgroupservie.NewGroupServiceReleaseMuteResult()
}

func getMuteStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexgroupservie.GroupServiceGetMuteStatusArgs)
	realResult := result.(*kitexgroupservie.GroupServiceGetMuteStatusResult)
	success, err := handler.(kitexgroupservie.GroupService).GetMuteStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGroupServiceGetMuteStatusArgs() interface{} {
	return kitexgroupservie.NewGroupServiceGetMuteStatusArgs()
}

func newGroupServiceGetMuteStatusResult() interface{} {
	return kitexgroupservie.NewGroupServiceGetMuteStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetGroupInfo(ctx context.Context, req *kitexgroupservie.GetGroupInfoReq) (r *kitexgroupservie.GetGroupInfoResp, err error) {
	var _args kitexgroupservie.GroupServiceGetGroupInfoArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetGroupInfoResult
	if err = p.c.Call(ctx, "GetGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeGroupInfo(ctx context.Context, req *kitexgroupservie.ChangeGroupInfoReq) (r *kitexgroupservie.ChangeGroupInfoResp, err error) {
	var _args kitexgroupservie.GroupServiceChangeGroupInfoArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceChangeGroupInfoResult
	if err = p.c.Call(ctx, "ChangeGroupInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchGroup(ctx context.Context, req *kitexgroupservie.SearchGroupReq) (r *kitexgroupservie.SearchGroupResp, err error) {
	var _args kitexgroupservie.GroupServiceSearchGroupArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceSearchGroupResult
	if err = p.c.Call(ctx, "SearchGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateGroup(ctx context.Context, req *kitexgroupservie.CreateGroupReq) (r *kitexgroupservie.CreateGroupResp, err error) {
	var _args kitexgroupservie.GroupServiceCreateGroupArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceCreateGroupResult
	if err = p.c.Call(ctx, "CreateGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteGroup(ctx context.Context, req *kitexgroupservie.DeleteGroupReq) (r *kitexgroupservie.DeleteGroupResp, err error) {
	var _args kitexgroupservie.GroupServiceDeleteGroupArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceDeleteGroupResult
	if err = p.c.Call(ctx, "DeleteGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LeaveGroup(ctx context.Context, req *kitexgroupservie.LeaveGroupReq) (r *kitexgroupservie.LeaveGroupResp, err error) {
	var _args kitexgroupservie.GroupServiceLeaveGroupArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceLeaveGroupResult
	if err = p.c.Call(ctx, "LeaveGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetGroupApply(ctx context.Context, req *kitexgroupservie.SetGroupApplyReq) (r *kitexgroupservie.SetGroupApplyResp, err error) {
	var _args kitexgroupservie.GroupServiceSetGroupApplyArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceSetGroupApplyResult
	if err = p.c.Call(ctx, "SetGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupApplyList(ctx context.Context, req *kitexgroupservie.GetGroupApplyListReq) (r *kitexgroupservie.GetGroupApplyListResp, err error) {
	var _args kitexgroupservie.GroupServiceGetGroupApplyListArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetGroupApplyListResult
	if err = p.c.Call(ctx, "GetGroupApplyList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLastVisitTime(ctx context.Context, req *kitexgroupservie.GetLastVisitTimeReq) (r *kitexgroupservie.GetLastVisitTimeResp, err error) {
	var _args kitexgroupservie.GroupServiceGetLastVisitTimeArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetLastVisitTimeResult
	if err = p.c.Call(ctx, "GetLastVisitTime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AgreeGroupApply(ctx context.Context, req *kitexgroupservie.AgreeGroupApplyReq) (r *kitexgroupservie.AgreeGroupApplyResp, err error) {
	var _args kitexgroupservie.GroupServiceAgreeGroupApplyArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceAgreeGroupApplyResult
	if err = p.c.Call(ctx, "AgreeGroupApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TransformGroupOwner(ctx context.Context, req *kitexgroupservie.TransformGroupOwnerReq) (r *kitexgroupservie.TransformGroupOwnerResp, err error) {
	var _args kitexgroupservie.GroupServiceTransformGroupOwnerArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceTransformGroupOwnerResult
	if err = p.c.Call(ctx, "TransformGroupOwner", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) KickOutGroup(ctx context.Context, req *kitexgroupservie.KickOutGroupReq) (r *kitexgroupservie.KickOutGroupResp, err error) {
	var _args kitexgroupservie.GroupServiceKickOutGroupArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceKickOutGroupResult
	if err = p.c.Call(ctx, "KickOutGroup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetManager(ctx context.Context, req *kitexgroupservie.SetManagerReq) (r *kitexgroupservie.SetManagerResp, err error) {
	var _args kitexgroupservie.GroupServiceSetManagerArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceSetManagerResult
	if err = p.c.Call(ctx, "SetManager", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeManager(ctx context.Context, req *kitexgroupservie.RevokeManagerReq) (r *kitexgroupservie.RevokeManagerResp, err error) {
	var _args kitexgroupservie.GroupServiceRevokeManagerArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceRevokeManagerResult
	if err = p.c.Call(ctx, "RevokeManager", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.GetGroupInfoWithUserReq) (r *kitexgroupservie.GetGroupInfoWithUserResp, err error) {
	var _args kitexgroupservie.GroupServiceGetGroupInfoWithUserArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetGroupInfoWithUserResult
	if err = p.c.Call(ctx, "GetGroupInfoWithUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateGroupInfoWithUser(ctx context.Context, req *kitexgroupservie.UpdateGroupInfoWithUserReq) (r *kitexgroupservie.UpdateGroupInfoWithUserResp, err error) {
	var _args kitexgroupservie.GroupServiceUpdateGroupInfoWithUserArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceUpdateGroupInfoWithUserResult
	if err = p.c.Call(ctx, "UpdateGroupInfoWithUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatSession(ctx context.Context, req *kitexgroupservie.CreatSessionReq) (r *kitexgroupservie.CreatSessionResp, err error) {
	var _args kitexgroupservie.GroupServiceCreatSessionArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceCreatSessionResult
	if err = p.c.Call(ctx, "CreatSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteSession(ctx context.Context, req *kitexgroupservie.DeleteSessionReq) (r *kitexgroupservie.DeleteSessionResp, err error) {
	var _args kitexgroupservie.GroupServiceDeleteSessionArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceDeleteSessionResult
	if err = p.c.Call(ctx, "DeleteSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendLastVisitTime(ctx context.Context, req *kitexgroupservie.GetFriendLastVisitTimeReq) (r *kitexgroupservie.GetFriendLastVisitTimeResp, err error) {
	var _args kitexgroupservie.GroupServiceGetFriendLastVisitTimeArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetFriendLastVisitTimeResult
	if err = p.c.Call(ctx, "GetFriendLastVisitTime", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ApplyForFriend(ctx context.Context, req *kitexgroupservie.ApplyForFriendReq) (r *kitexgroupservie.ApplyForFriendResp, err error) {
	var _args kitexgroupservie.GroupServiceApplyForFriendArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceApplyForFriendResult
	if err = p.c.Call(ctx, "ApplyForFriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendApplyList(ctx context.Context, req *kitexgroupservie.GetFriendApplyListReq) (r *kitexgroupservie.GetFriendApplyListResp, err error) {
	var _args kitexgroupservie.GroupServiceGetFriendApplyListArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetFriendApplyListResult
	if err = p.c.Call(ctx, "GetFriendApplyList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefuseFriendApply(ctx context.Context, req *kitexgroupservie.RefuseFriendApplyReq) (r *kitexgroupservie.RefuseFriendApplyResp, err error) {
	var _args kitexgroupservie.GroupServiceRefuseFriendApplyArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceRefuseFriendApplyResult
	if err = p.c.Call(ctx, "RefuseFriendApply", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetGroupAndSessionID(ctx context.Context, req *kitexgroupservie.GetGroupAndSessionIDReq) (r *kitexgroupservie.GetGroupAndSessionIDResp, err error) {
	var _args kitexgroupservie.GroupServiceGetGroupAndSessionIDArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetGroupAndSessionIDResult
	if err = p.c.Call(ctx, "GetGroupAndSessionID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetMute(ctx context.Context, req *kitexgroupservie.SetMuteReq) (r *kitexgroupservie.SetMuteResp, err error) {
	var _args kitexgroupservie.GroupServiceSetMuteArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceSetMuteResult
	if err = p.c.Call(ctx, "SetMute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseMute(ctx context.Context, req *kitexgroupservie.ReleaseMuteReq) (r *kitexgroupservie.ReleaseMuteResp, err error) {
	var _args kitexgroupservie.GroupServiceReleaseMuteArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceReleaseMuteResult
	if err = p.c.Call(ctx, "ReleaseMute", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMuteStatus(ctx context.Context, req *kitexgroupservie.GetMuteStatusReq) (r *kitexgroupservie.GetMuteStatusResp, err error) {
	var _args kitexgroupservie.GroupServiceGetMuteStatusArgs
	_args.Req = req
	var _result kitexgroupservie.GroupServiceGetMuteStatusResult
	if err = p.c.Call(ctx, "GetMuteStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
