// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexcommonmodel

import (
	"fmt"
)

type UserInfo struct {
	UserID        int64  `thrift:"UserID,1" frugal:"1,default,i64" json:"UserID"`
	UserName      string `thrift:"UserName,2" frugal:"2,default,string" json:"UserName"`
	Introduction  string `thrift:"Introduction,3" frugal:"3,default,string" json:"Introduction"`
	BirthdayYear  int64  `thrift:"BirthdayYear,4" frugal:"4,default,i64" json:"BirthdayYear"`
	BirthdayMonth int64  `thrift:"BirthdayMonth,5" frugal:"5,default,i64" json:"BirthdayMonth"`
	BirthdayDay   int64  `thrift:"BirthdayDay,6" frugal:"6,default,i64" json:"BirthdayDay"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserID() (v int64) {
	return p.UserID
}

func (p *UserInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *UserInfo) GetIntroduction() (v string) {
	return p.Introduction
}

func (p *UserInfo) GetBirthdayYear() (v int64) {
	return p.BirthdayYear
}

func (p *UserInfo) GetBirthdayMonth() (v int64) {
	return p.BirthdayMonth
}

func (p *UserInfo) GetBirthdayDay() (v int64) {
	return p.BirthdayDay
}
func (p *UserInfo) SetUserID(val int64) {
	p.UserID = val
}
func (p *UserInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *UserInfo) SetIntroduction(val string) {
	p.Introduction = val
}
func (p *UserInfo) SetBirthdayYear(val int64) {
	p.BirthdayYear = val
}
func (p *UserInfo) SetBirthdayMonth(val int64) {
	p.BirthdayMonth = val
}
func (p *UserInfo) SetBirthdayDay(val int64) {
	p.BirthdayDay = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "UserID",
	2: "UserName",
	3: "Introduction",
	4: "BirthdayYear",
	5: "BirthdayMonth",
	6: "BirthdayDay",
}

type UserLoginInfo struct {
	UserID   int64  `thrift:"UserID,1" frugal:"1,default,i64" json:"UserID"`
	Password string `thrift:"Password,2" frugal:"2,default,string" json:"Password"`
	Salt     string `thrift:"Salt,3" frugal:"3,default,string" json:"Salt"`
}

func NewUserLoginInfo() *UserLoginInfo {
	return &UserLoginInfo{}
}

func (p *UserLoginInfo) InitDefault() {
}

func (p *UserLoginInfo) GetUserID() (v int64) {
	return p.UserID
}

func (p *UserLoginInfo) GetPassword() (v string) {
	return p.Password
}

func (p *UserLoginInfo) GetSalt() (v string) {
	return p.Salt
}
func (p *UserLoginInfo) SetUserID(val int64) {
	p.UserID = val
}
func (p *UserLoginInfo) SetPassword(val string) {
	p.Password = val
}
func (p *UserLoginInfo) SetSalt(val string) {
	p.Salt = val
}

func (p *UserLoginInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginInfo(%+v)", *p)
}

var fieldIDToName_UserLoginInfo = map[int16]string{
	1: "UserID",
	2: "Password",
	3: "Salt",
}

type RemarkInfo struct {
	UserID     int64  `thrift:"UserID,1" frugal:"1,default,i64" json:"UserID"`
	GoalUserID int64  `thrift:"GoalUserID,2" frugal:"2,default,i64" json:"GoalUserID"`
	NickName   string `thrift:"NickName,3" frugal:"3,default,string" json:"NickName"`
}

func NewRemarkInfo() *RemarkInfo {
	return &RemarkInfo{}
}

func (p *RemarkInfo) InitDefault() {
}

func (p *RemarkInfo) GetUserID() (v int64) {
	return p.UserID
}

func (p *RemarkInfo) GetGoalUserID() (v int64) {
	return p.GoalUserID
}

func (p *RemarkInfo) GetNickName() (v string) {
	return p.NickName
}
func (p *RemarkInfo) SetUserID(val int64) {
	p.UserID = val
}
func (p *RemarkInfo) SetGoalUserID(val int64) {
	p.GoalUserID = val
}
func (p *RemarkInfo) SetNickName(val string) {
	p.NickName = val
}

func (p *RemarkInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemarkInfo(%+v)", *p)
}

var fieldIDToName_RemarkInfo = map[int16]string{
	1: "UserID",
	2: "GoalUserID",
	3: "NickName",
}
