// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexcommonmodel

import (
	"fmt"
)

type CommonInfo struct {
	Trace string `thrift:"trace,1" frugal:"1,default,string" json:"trace"`
}

func NewCommonInfo() *CommonInfo {
	return &CommonInfo{}
}

func (p *CommonInfo) InitDefault() {
}

func (p *CommonInfo) GetTrace() (v string) {
	return p.Trace
}
func (p *CommonInfo) SetTrace(val string) {
	p.Trace = val
}

func (p *CommonInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonInfo(%+v)", *p)
}

var fieldIDToName_CommonInfo = map[int16]string{
	1: "trace",
}
