// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package kitexuserservice

import (
	"aim/kitex_gen/kitexcommonmodel"
	"context"
	"fmt"
)

type GetUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

var GetUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetUserInfoReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetUserInfoReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "common_info",
	2: "user_id",
}

type GetUserInfoResp struct {
	UserInfo   *kitexcommonmodel.UserInfo     `thrift:"user_info,1" frugal:"1,default,kitexcommonmodel.UserInfo" json:"user_info"`
	RemarkInfo []*kitexcommonmodel.RemarkInfo `thrift:"remark_info,2" frugal:"2,default,list<kitexcommonmodel.RemarkInfo>" json:"remark_info"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

var GetUserInfoResp_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *GetUserInfoResp) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}

func (p *GetUserInfoResp) GetRemarkInfo() (v []*kitexcommonmodel.RemarkInfo) {
	return p.RemarkInfo
}
func (p *GetUserInfoResp) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}
func (p *GetUserInfoResp) SetRemarkInfo(val []*kitexcommonmodel.RemarkInfo) {
	p.RemarkInfo = val
}

func (p *GetUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "user_info",
	2: "remark_info",
}

type GetOtherUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	GoalUserId int64                        `thrift:"goal_user_id,2" frugal:"2,default,i64" json:"goal_user_id"`
}

func NewGetOtherUserInfoReq() *GetOtherUserInfoReq {
	return &GetOtherUserInfoReq{}
}

func (p *GetOtherUserInfoReq) InitDefault() {
}

var GetOtherUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *GetOtherUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return GetOtherUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *GetOtherUserInfoReq) GetGoalUserId() (v int64) {
	return p.GoalUserId
}
func (p *GetOtherUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *GetOtherUserInfoReq) SetGoalUserId(val int64) {
	p.GoalUserId = val
}

func (p *GetOtherUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *GetOtherUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOtherUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetOtherUserInfoReq = map[int16]string{
	1: "common_info",
	2: "goal_user_id",
}

type GetOtherUserInfoResp struct {
	UserInfo *kitexcommonmodel.UserInfo `thrift:"user_info,1" frugal:"1,default,kitexcommonmodel.UserInfo" json:"user_info"`
}

func NewGetOtherUserInfoResp() *GetOtherUserInfoResp {
	return &GetOtherUserInfoResp{}
}

func (p *GetOtherUserInfoResp) InitDefault() {
}

var GetOtherUserInfoResp_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *GetOtherUserInfoResp) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return GetOtherUserInfoResp_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetOtherUserInfoResp) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}

func (p *GetOtherUserInfoResp) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetOtherUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOtherUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetOtherUserInfoResp = map[int16]string{
	1: "user_info",
}

type UpdateUserInfoReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserInfo   *kitexcommonmodel.UserInfo   `thrift:"user_info,2" frugal:"2,default,kitexcommonmodel.UserInfo" json:"user_info"`
}

func NewUpdateUserInfoReq() *UpdateUserInfoReq {
	return &UpdateUserInfoReq{}
}

func (p *UpdateUserInfoReq) InitDefault() {
}

var UpdateUserInfoReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *UpdateUserInfoReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return UpdateUserInfoReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

var UpdateUserInfoReq_UserInfo_DEFAULT *kitexcommonmodel.UserInfo

func (p *UpdateUserInfoReq) GetUserInfo() (v *kitexcommonmodel.UserInfo) {
	if !p.IsSetUserInfo() {
		return UpdateUserInfoReq_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *UpdateUserInfoReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *UpdateUserInfoReq) SetUserInfo(val *kitexcommonmodel.UserInfo) {
	p.UserInfo = val
}

func (p *UpdateUserInfoReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *UpdateUserInfoReq) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *UpdateUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoReq(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoReq = map[int16]string{
	1: "common_info",
	2: "user_info",
}

type UpdateUserInfoResp struct {
}

func NewUpdateUserInfoResp() *UpdateUserInfoResp {
	return &UpdateUserInfoResp{}
}

func (p *UpdateUserInfoResp) InitDefault() {
}

func (p *UpdateUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInfoResp(%+v)", *p)
}

var fieldIDToName_UpdateUserInfoResp = map[int16]string{}

type RemarkReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	RemarkInfo *kitexcommonmodel.RemarkInfo `thrift:"remark_info,2" frugal:"2,default,kitexcommonmodel.RemarkInfo" json:"remark_info"`
}

func NewRemarkReq() *RemarkReq {
	return &RemarkReq{}
}

func (p *RemarkReq) InitDefault() {
}

var RemarkReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *RemarkReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return RemarkReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

var RemarkReq_RemarkInfo_DEFAULT *kitexcommonmodel.RemarkInfo

func (p *RemarkReq) GetRemarkInfo() (v *kitexcommonmodel.RemarkInfo) {
	if !p.IsSetRemarkInfo() {
		return RemarkReq_RemarkInfo_DEFAULT
	}
	return p.RemarkInfo
}
func (p *RemarkReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *RemarkReq) SetRemarkInfo(val *kitexcommonmodel.RemarkInfo) {
	p.RemarkInfo = val
}

func (p *RemarkReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *RemarkReq) IsSetRemarkInfo() bool {
	return p.RemarkInfo != nil
}

func (p *RemarkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemarkReq(%+v)", *p)
}

var fieldIDToName_RemarkReq = map[int16]string{
	1: "common_info",
	2: "remark_info",
}

type RemarkResp struct {
}

func NewRemarkResp() *RemarkResp {
	return &RemarkResp{}
}

func (p *RemarkResp) InitDefault() {
}

func (p *RemarkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RemarkResp(%+v)", *p)
}

var fieldIDToName_RemarkResp = map[int16]string{}

type RegisterReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	Password   string                       `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

var RegisterReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *RegisterReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return RegisterReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "common_info",
	2: "password",
}

type RegisterResp struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

func (p *RegisterResp) GetUserId() (v int64) {
	return p.UserId
}
func (p *RegisterResp) SetUserId(val int64) {
	p.UserId = val
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "user_id",
}

type LoginReq struct {
	CommonInfo *kitexcommonmodel.CommonInfo `thrift:"common_info,1" frugal:"1,default,kitexcommonmodel.CommonInfo" json:"common_info"`
	UserId     int64                        `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	Password   string                       `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

var LoginReq_CommonInfo_DEFAULT *kitexcommonmodel.CommonInfo

func (p *LoginReq) GetCommonInfo() (v *kitexcommonmodel.CommonInfo) {
	if !p.IsSetCommonInfo() {
		return LoginReq_CommonInfo_DEFAULT
	}
	return p.CommonInfo
}

func (p *LoginReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetCommonInfo(val *kitexcommonmodel.CommonInfo) {
	p.CommonInfo = val
}
func (p *LoginReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) IsSetCommonInfo() bool {
	return p.CommonInfo != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "common_info",
	2: "user_id",
	3: "password",
}

type LoginResp struct {
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{}

type UserService interface {
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	GetOtherUserInfo(ctx context.Context, req *GetOtherUserInfoReq) (r *GetOtherUserInfoResp, err error)

	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (r *UpdateUserInfoResp, err error)

	Remark(ctx context.Context, req *RemarkReq) (r *RemarkResp, err error)

	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)
}

type UserServiceGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserServiceGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceGetOtherUserInfoArgs struct {
	Req *GetOtherUserInfoReq `thrift:"req,1" frugal:"1,default,GetOtherUserInfoReq" json:"req"`
}

func NewUserServiceGetOtherUserInfoArgs() *UserServiceGetOtherUserInfoArgs {
	return &UserServiceGetOtherUserInfoArgs{}
}

func (p *UserServiceGetOtherUserInfoArgs) InitDefault() {
}

var UserServiceGetOtherUserInfoArgs_Req_DEFAULT *GetOtherUserInfoReq

func (p *UserServiceGetOtherUserInfoArgs) GetReq() (v *GetOtherUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceGetOtherUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetOtherUserInfoArgs) SetReq(val *GetOtherUserInfoReq) {
	p.Req = val
}

func (p *UserServiceGetOtherUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetOtherUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetOtherUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetOtherUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceGetOtherUserInfoResult struct {
	Success *GetOtherUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetOtherUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceGetOtherUserInfoResult() *UserServiceGetOtherUserInfoResult {
	return &UserServiceGetOtherUserInfoResult{}
}

func (p *UserServiceGetOtherUserInfoResult) InitDefault() {
}

var UserServiceGetOtherUserInfoResult_Success_DEFAULT *GetOtherUserInfoResp

func (p *UserServiceGetOtherUserInfoResult) GetSuccess() (v *GetOtherUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetOtherUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetOtherUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOtherUserInfoResp)
}

func (p *UserServiceGetOtherUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetOtherUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetOtherUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetOtherUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserInfoArgs struct {
	Req *UpdateUserInfoReq `thrift:"req,1" frugal:"1,default,UpdateUserInfoReq" json:"req"`
}

func NewUserServiceUpdateUserInfoArgs() *UserServiceUpdateUserInfoArgs {
	return &UserServiceUpdateUserInfoArgs{}
}

func (p *UserServiceUpdateUserInfoArgs) InitDefault() {
}

var UserServiceUpdateUserInfoArgs_Req_DEFAULT *UpdateUserInfoReq

func (p *UserServiceUpdateUserInfoArgs) GetReq() (v *UpdateUserInfoReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserInfoArgs) SetReq(val *UpdateUserInfoReq) {
	p.Req = val
}

func (p *UserServiceUpdateUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserInfoResult struct {
	Success *UpdateUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInfoResp" json:"success,omitempty"`
}

func NewUserServiceUpdateUserInfoResult() *UserServiceUpdateUserInfoResult {
	return &UserServiceUpdateUserInfoResult{}
}

func (p *UserServiceUpdateUserInfoResult) InitDefault() {
}

var UserServiceUpdateUserInfoResult_Success_DEFAULT *UpdateUserInfoResp

func (p *UserServiceUpdateUserInfoResult) GetSuccess() (v *UpdateUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInfoResp)
}

func (p *UserServiceUpdateUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserInfoResult = map[int16]string{
	0: "success",
}

type UserServiceRemarkArgs struct {
	Req *RemarkReq `thrift:"req,1" frugal:"1,default,RemarkReq" json:"req"`
}

func NewUserServiceRemarkArgs() *UserServiceRemarkArgs {
	return &UserServiceRemarkArgs{}
}

func (p *UserServiceRemarkArgs) InitDefault() {
}

var UserServiceRemarkArgs_Req_DEFAULT *RemarkReq

func (p *UserServiceRemarkArgs) GetReq() (v *RemarkReq) {
	if !p.IsSetReq() {
		return UserServiceRemarkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRemarkArgs) SetReq(val *RemarkReq) {
	p.Req = val
}

func (p *UserServiceRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRemarkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRemarkArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRemarkArgs = map[int16]string{
	1: "req",
}

type UserServiceRemarkResult struct {
	Success *RemarkResp `thrift:"success,0,optional" frugal:"0,optional,RemarkResp" json:"success,omitempty"`
}

func NewUserServiceRemarkResult() *UserServiceRemarkResult {
	return &UserServiceRemarkResult{}
}

func (p *UserServiceRemarkResult) InitDefault() {
}

var UserServiceRemarkResult_Success_DEFAULT *RemarkResp

func (p *UserServiceRemarkResult) GetSuccess() (v *RemarkResp) {
	if !p.IsSetSuccess() {
		return UserServiceRemarkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*RemarkResp)
}

func (p *UserServiceRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRemarkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRemarkResult(%+v)", *p)
}

var fieldIDToName_UserServiceRemarkResult = map[int16]string{
	0: "success",
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}
