// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	kitexuserservice "aim/kitex_gen/kitexuserservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUserInfo(ctx context.Context, req *kitexuserservice.GetUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.GetUserInfoResp, err error)
	GetOtherUserInfo(ctx context.Context, req *kitexuserservice.GetOtherUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.GetOtherUserInfoResp, err error)
	UpdateUserInfo(ctx context.Context, req *kitexuserservice.UpdateUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.UpdateUserInfoResp, err error)
	Remark(ctx context.Context, req *kitexuserservice.RemarkReq, callOptions ...callopt.Option) (r *kitexuserservice.RemarkResp, err error)
	Register(ctx context.Context, req *kitexuserservice.RegisterReq, callOptions ...callopt.Option) (r *kitexuserservice.RegisterResp, err error)
	Login(ctx context.Context, req *kitexuserservice.LoginReq, callOptions ...callopt.Option) (r *kitexuserservice.LoginResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) GetUserInfo(ctx context.Context, req *kitexuserservice.GetUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kUserServiceClient) GetOtherUserInfo(ctx context.Context, req *kitexuserservice.GetOtherUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.GetOtherUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOtherUserInfo(ctx, req)
}

func (p *kUserServiceClient) UpdateUserInfo(ctx context.Context, req *kitexuserservice.UpdateUserInfoReq, callOptions ...callopt.Option) (r *kitexuserservice.UpdateUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, req)
}

func (p *kUserServiceClient) Remark(ctx context.Context, req *kitexuserservice.RemarkReq, callOptions ...callopt.Option) (r *kitexuserservice.RemarkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Remark(ctx, req)
}

func (p *kUserServiceClient) Register(ctx context.Context, req *kitexuserservice.RegisterReq, callOptions ...callopt.Option) (r *kitexuserservice.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *kitexuserservice.LoginReq, callOptions ...callopt.Option) (r *kitexuserservice.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}
