// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	kitexuserservice "aim/kitex_gen/kitexuserservice"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserServiceGetUserInfoArgs,
		newUserServiceGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOtherUserInfo": kitex.NewMethodInfo(
		getOtherUserInfoHandler,
		newUserServiceGetOtherUserInfoArgs,
		newUserServiceGetOtherUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInfo": kitex.NewMethodInfo(
		updateUserInfoHandler,
		newUserServiceUpdateUserInfoArgs,
		newUserServiceUpdateUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Remark": kitex.NewMethodInfo(
		remarkHandler,
		newUserServiceRemarkArgs,
		newUserServiceRemarkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*kitexuserservice.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "kitexuserservice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceGetUserInfoArgs)
	realResult := result.(*kitexuserservice.UserServiceGetUserInfoResult)
	success, err := handler.(kitexuserservice.UserService).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserInfoArgs() interface{} {
	return kitexuserservice.NewUserServiceGetUserInfoArgs()
}

func newUserServiceGetUserInfoResult() interface{} {
	return kitexuserservice.NewUserServiceGetUserInfoResult()
}

func getOtherUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceGetOtherUserInfoArgs)
	realResult := result.(*kitexuserservice.UserServiceGetOtherUserInfoResult)
	success, err := handler.(kitexuserservice.UserService).GetOtherUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetOtherUserInfoArgs() interface{} {
	return kitexuserservice.NewUserServiceGetOtherUserInfoArgs()
}

func newUserServiceGetOtherUserInfoResult() interface{} {
	return kitexuserservice.NewUserServiceGetOtherUserInfoResult()
}

func updateUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceUpdateUserInfoArgs)
	realResult := result.(*kitexuserservice.UserServiceUpdateUserInfoResult)
	success, err := handler.(kitexuserservice.UserService).UpdateUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserInfoArgs() interface{} {
	return kitexuserservice.NewUserServiceUpdateUserInfoArgs()
}

func newUserServiceUpdateUserInfoResult() interface{} {
	return kitexuserservice.NewUserServiceUpdateUserInfoResult()
}

func remarkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceRemarkArgs)
	realResult := result.(*kitexuserservice.UserServiceRemarkResult)
	success, err := handler.(kitexuserservice.UserService).Remark(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRemarkArgs() interface{} {
	return kitexuserservice.NewUserServiceRemarkArgs()
}

func newUserServiceRemarkResult() interface{} {
	return kitexuserservice.NewUserServiceRemarkResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceRegisterArgs)
	realResult := result.(*kitexuserservice.UserServiceRegisterResult)
	success, err := handler.(kitexuserservice.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return kitexuserservice.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return kitexuserservice.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*kitexuserservice.UserServiceLoginArgs)
	realResult := result.(*kitexuserservice.UserServiceLoginResult)
	success, err := handler.(kitexuserservice.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return kitexuserservice.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return kitexuserservice.NewUserServiceLoginResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUserInfo(ctx context.Context, req *kitexuserservice.GetUserInfoReq) (r *kitexuserservice.GetUserInfoResp, err error) {
	var _args kitexuserservice.UserServiceGetUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOtherUserInfo(ctx context.Context, req *kitexuserservice.GetOtherUserInfoReq) (r *kitexuserservice.GetOtherUserInfoResp, err error) {
	var _args kitexuserservice.UserServiceGetOtherUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceGetOtherUserInfoResult
	if err = p.c.Call(ctx, "GetOtherUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInfo(ctx context.Context, req *kitexuserservice.UpdateUserInfoReq) (r *kitexuserservice.UpdateUserInfoResp, err error) {
	var _args kitexuserservice.UserServiceUpdateUserInfoArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceUpdateUserInfoResult
	if err = p.c.Call(ctx, "UpdateUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Remark(ctx context.Context, req *kitexuserservice.RemarkReq) (r *kitexuserservice.RemarkResp, err error) {
	var _args kitexuserservice.UserServiceRemarkArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceRemarkResult
	if err = p.c.Call(ctx, "Remark", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *kitexuserservice.RegisterReq) (r *kitexuserservice.RegisterResp, err error) {
	var _args kitexuserservice.UserServiceRegisterArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *kitexuserservice.LoginReq) (r *kitexuserservice.LoginResp, err error) {
	var _args kitexuserservice.UserServiceLoginArgs
	_args.Req = req
	var _result kitexuserservice.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
